services:
  - type: web
    name: phant0m-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node discord_bot.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: 3000
